package splusjava;

/** GENERATED by the reference SPlusthon implementation (python) - obfuscated transport ground truth. */
final class ObfsVectors {
    private ObfsVectors() {}
    static final String RANDOM64 = "41424344010203048b9cadbecfe0f102132435465768798a9bacbdcedff00112233445566778899aabbccddeef00112233445566778899aabbccddeeff102132";
    static final String HEADER = "41424344010203048b9cadbecfe0f102132435465768798a9bacbdcedff00112233445566778899aabbccddeef00112233445566778899aabfbc9086985cafd7";
    static final String SAMPLE = "0b2845627f9cb9d6f3102d4a6784a1bedbf815324f6c89a6c3e0fd1a3754718eabc8e5021f";
    static final String ENCRYPTED = "abac72c556d523b43ee5ed78c3a666c703888dca035d935aedc34ca09e341765fc36e25152";
}
