#!/usr/bin/env python3
"""
Generates the schema/key data classes used by splusjava from a SPlusthon checkout.

Usage:
    python3 tools/gen_schema.py /path/to/SPlusthon-main

Outputs (relative to this repository):
    src/main/java/splusjava/tl/SchemaData.java
    src/main/java/splusjava/crypto/RsaKeyData.java

The TL schema is embedded as text (one constructor per line) because Java
class files cannot hold a String constant larger than 64 KiB, so it is split
in chunks. The runtime parses it lazily (see splusjava.tl.TLSchema).
"""
import base64
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def read(path):
    with open(path, encoding='utf-8') as f:
        return f.read()


def collect_lines(path, api_layer):
    """Yield (kind, definition) for every constructor line with an explicit id."""
    is_function = False
    for raw in read(path).splitlines():
        line = raw.strip()
        if not line or line.startswith('//'):
            continue
        if line == '---functions---':
            is_function = True
            continue
        if line == '---types---':
            is_function = False
            continue
        if '#' not in line.split(' ')[0]:
            continue  # no explicit constructor id (unused TlsBlock helpers)
        if not line.endswith(';'):
            raise ValueError('unexpected line: %r' % line)
        line = re.sub(r'\s+', ' ', line[:-1].strip())
        # api.tl -> 'T'/'F' (strings are real strings)
        # mtproto.tl -> 't'/'f' (strings are raw bytes)
        if api_layer:
            kind = 'F' if is_function else 'T'
        else:
            kind = 'f' if is_function else 't'
        yield kind, line


# Handled natively by the codec, so they must not be defined by the schema.
SKIP_NAMES = {'vector', 'true', 'null', 'boolTrue', 'boolFalse'}


def split_chunks(lines, limit=50000):
    chunks, cur, size = [], [], 0
    for line in lines:
        n = len(line.encode('utf-8')) + 1
        if size + n > limit and cur:
            chunks.append(cur)
            cur, size = [], 0
        cur.append(line)
        size += n
    if cur:
        chunks.append(cur)
    return chunks


def java_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n') + '"'


def gen_schema(repo):
    api = os.path.join(repo, 'splusthon_generator', 'data', 'api.tl')
    mt = os.path.join(repo, 'splusthon_generator', 'data', 'mtproto.tl')
    layer = int(re.search(r'LAYER\s+(\d+)', read(api)).group(1))

    entries = []
    seen_ids = set()
    for path, is_api in ((mt, False), (api, True)):
        for kind, line in collect_lines(path, is_api):
            m = re.match(r'([\w.]+)#([0-9a-fA-F]+)', line)
            name, cid = m.group(1), int(m.group(2), 16)
            if name in SKIP_NAMES:
                continue
            if cid in seen_ids:
                continue
            seen_ids.add(cid)
            entries.append('%s %s' % (kind, line))

    chunks = split_chunks(entries)
    out = []
    out.append('package splusjava.tl;\n')
    out.append('/**\n * GENERATED by tools/gen_schema.py - do not edit by hand.\n'
               ' * TL schema of Soroush Plus (layer %d) + MTProto service schema.\n'
               ' * Line format: "&lt;kind&gt; &lt;tl definition&gt;" where kind is\n'
               ' * T/F = API type/function, t/f = MTProto type/function (strings are bytes).\n */\n' % layer)
    out.append('final class SchemaData {')
    out.append('    private SchemaData() {}')
    out.append('    static final int LAYER = %d;' % layer)
    out.append('    static final int COUNT = %d;' % len(entries))
    for i, ch in enumerate(chunks):
        out.append('    private static final String C%d =' % i)
        for j, line in enumerate(ch):
            last = j == len(ch) - 1
            out.append('        %s%s' % (java_str(line + '\n'), ';' if last else ' +'))
    out.append('    static final String[] CHUNKS = { %s };' %
               ', '.join('C%d' % i for i in range(len(chunks))))
    out.append('}')
    path = os.path.join(ROOT, 'src/main/java/splusjava/tl/SchemaData.java')
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(out) + '\n')
    print('schema: %d constructors, %d chunk(s), layer %d' % (len(entries), len(chunks), layer))


def der_read(buf, i):
    i += 1  # tag
    l = buf[i]
    i += 1
    if l & 0x80:
        nb = l & 0x7f
        l = int.from_bytes(buf[i:i + nb], 'big')
        i += nb
    return buf[i:i + l], i + l


def gen_keys(repo):
    text = read(os.path.join(repo, 'splusthon', 'crypto', 'rsa.py'))
    keys = []
    for m in re.finditer(r'-----BEGIN RSA PUBLIC KEY-----(.*?)-----END RSA PUBLIC KEY-----', text, re.S):
        der = base64.b64decode(''.join(m.group(1).split()))
        body, _ = der_read(der, 0)
        n, j = der_read(body, 0)
        e, _ = der_read(body, j)
        keys.append((int.from_bytes(n, 'big'), int.from_bytes(e, 'big')))
    out = ['package splusjava.crypto;\n',
           '/** GENERATED by tools/gen_schema.py - Soroush Plus server RSA public keys (n, e as hex). */',
           'final class RsaKeyData {',
           '    private RsaKeyData() {}',
           '    static final String[][] KEYS = {']
    for n, e in keys:
        out.append('        { "%x", "%x" },' % (n, e))
    out.append('    };')
    out.append('}')
    path = os.path.join(ROOT, 'src/main/java/splusjava/crypto/RsaKeyData.java')
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(out) + '\n')
    print('rsa keys: %d' % len(keys))


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)
    gen_schema(sys.argv[1])
    gen_keys(sys.argv[1])
